export interface InitialMedicineData {
  name: string;
  teguhanMax: number;
  jogorogoMax: number;
}

export const initialMedicines: InitialMedicineData[] = [
  { name: 'ACETYLCYSTEINE CAP', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'ACYCLOVIR TAB 400MG', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'AMLODIPIN TAB 10MG', teguhanMax: 150, jogorogoMax: 150 },
  { name: 'AMLODIPIN TAB 5MG', teguhanMax: 150, jogorogoMax: 150 },
  { name: 'AMOXICILLIN SIRUP', teguhanMax: 7, jogorogoMax: 7 },
  { name: 'AMOXILLIN TAB 500MG', teguhanMax: 200, jogorogoMax: 200 },
  { name: 'ASAM MEFENAMAT 500 MG', teguhanMax: 150, jogorogoMax: 150 },
  { name: 'ASAM TRANEXAMAT 500MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'ATTAPULGIT', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'ALOPURINOL 100 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'AMBROXOL TAB 30MG', teguhanMax: 150, jogorogoMax: 150 },
  { name: 'AMBROXOL SIRUP', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'ACYCLOVIR CREAM', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'ALCOHOL SWAB', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'ASAM TRANEXAMAT AMP', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'BETAHISTIN TAB 6MG', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'BISOPROLOL TAB 2,5MG', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'BISOPROLOL TAB 5MG', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'BUFACORT - N CREAM', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'BUFANTACID TAB', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'BRONCHITIN TAB', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'BROCHIFAR PLUS TAB', teguhanMax: 200, jogorogoMax: 200 },
  { name: 'BUFACOMB CREAM', teguhanMax: 2, jogorogoMax: 2 },
  { name: 'BYE BYE FEVER', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'BIOMAG MPS TAB', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CANDESARTAN TAB 16MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CANDESARTAN TAB 8MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CETIRIZIN TAB 10MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CETIRIZIN SIRUP', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'CEFIXIME 100MG', teguhanMax: 150, jogorogoMax: 150 },
  { name: 'CEFIXIME 200MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CEFIXIME SIRUP', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'CEFTRIAXONE VIAL', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'CIPROFLOXACIN TAB 500MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CLOPIDOGREL TAB 75MG', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'CLINDAMYCIN TAB 300MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CODEIN TAB 10MG', teguhanMax: 20, jogorogoMax: 20 },
  { name: 'COTRIMOXAZOLE TAB 960', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CARMED CREAM', teguhanMax: 1, jogorogoMax: 1 },
  { name: 'CHLORAMPHENICOL CAP 250 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CEFADROXIL SIRUP', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'CAPTROPIL TAB 12.5 MG', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'CAPTROPIL TAB 25 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'CURCUMA FORTE', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'CHLORAMPHENICOL SIRUP', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'CYANOCOBALAMIN VIAL', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'COMBIVENT', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'CHLORPROMAZINE TAB 100MG', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'CLOBETASOL CREAM 0.05%', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'DEXAMETASONE TAB 0,5MG', teguhanMax: 200, jogorogoMax: 200 },
  { name: 'DEXAMETASONE TAB 0,75MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'DIAZEPAM TAB 2MG', teguhanMax: 20, jogorogoMax: 20 },
  { name: 'DIMENHIDRINATE TAB 50 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'DEMACOLIN', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'DOMPERIDONE 10 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'DICLOFENAC POTASIUM 50 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'DANEURON', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'DICLOFENAC CREAM', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'DIPENHYDRAMINE HCL', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'DEXAMETHASONE AMP', teguhanMax: 20, jogorogoMax: 20 },
  { name: 'DERMA PLAST', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'EPERISONE TAB 50 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'EPINEPHRINE AMP', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'FLUNARIZIN TAB', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'FUROSEMIDE TAB 40MG', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'FOLIC ACID TAB', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'GABAPENTIN CAP 100MG', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'GLIMEPIRIDE TAB 4 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'GLIMEPIRIDE TAB 2 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'GUAIFENESIN TAB 100 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'GENTAMICIN SULFATE 0.1%', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'GOM', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'GEL', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'HYPAVIX', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'HUFAMAG SIRUP', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'IBUPROFEN 400MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'IBUPROFEN SIRUP', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'INFUS SET', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'ISOSORBIDE DINITRATE', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'KETOKONAZOLE 200MG', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'KETOCONAZOLE CREAM', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'KETOROLAC AMP', teguhanMax: 20, jogorogoMax: 20 },
  { name: 'KASSA', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'KETOPROFEN AMP', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'LANSOPRAZOLE 30 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'LEVOFLOXACIN 500MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'LIDOCAINE AMP', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'MELOXICAM 15MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'MEROPENEM VIAL', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'METRONIDAZOLE TAB 500MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'METYLPREDNISOLON 4MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'METYLPREDNISOLON 8MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'METRONIDAZOLE INFUS', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'METRONIDAZOLE SIRUP', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'METAMIZOLE VIAL', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'METFORMIN 500 MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'MIZONAZOLE 2% CREAM', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'NACL INFUS 0,9%', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'NUFACORT CREAM', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'OMEPRAZOLE 20MG CAP', teguhanMax: 200, jogorogoMax: 100 },
  { name: 'ONDANSETRON TAB 4MG', teguhanMax: 200, jogorogoMax: 100 },
  { name: 'ONDANCENTRON AMP', teguhanMax: 20, jogorogoMax: 20 },
  { name: 'OMEPRAZOLE VIAL', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'PANTOPRAZOLE VIAL', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'PARACETAMOL INFUS', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'PARACETAMOL SIRUP', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'PARACETAMOL TAB 500MG', teguhanMax: 200, jogorogoMax: 200 },
  { name: 'PLESTERIN', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'PRONEURON', teguhanMax: 20, jogorogoMax: 20 },
  { name: 'PERMETHRIN 5%', teguhanMax: 2, jogorogoMax: 2 },
  { name: 'PEHACAIN', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'RANITIDIN TAB 150MG', teguhanMax: 200, jogorogoMax: 200 },
  { name: 'RECODRYL HCL VIAL', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'RL INFUS', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'RANITIDINE AMP', teguhanMax: 30, jogorogoMax: 30 },
  { name: 'RIVANOL', teguhanMax: 1, jogorogoMax: 1 },
  { name: 'SALBUTAMOL 2MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'SALBUTAMOL 4MG', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'SIMVASTATIN 10MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'SPASMINAL (PCT + HYOSCINE)', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'SALBUTAMOL SIRUP', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'SPUIT 1 CC', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'SPUIT 3 CC', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'SPUIT 5 CC', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'SPUIT 10 CC', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'STRIP ASAM URAT', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'STRIP GULA', teguhanMax: 25, jogorogoMax: 25 },
  { name: 'STRIP KOLESTEROL', teguhanMax: 10, jogorogoMax: 10 },
  { name: 'THIAMPHENICOL', teguhanMax: 150, jogorogoMax: 150 },
  { name: 'VITAMIN C', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'VENFLON 18G', teguhanMax: 5, jogorogoMax: 5 },
  { name: 'VENFLON 24G', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'WING NEEDLE NO 25', teguhanMax: 50, jogorogoMax: 50 },
  { name: 'ZINC 10MG', teguhanMax: 100, jogorogoMax: 100 },
  { name: 'ZINC 20MG', teguhanMax: 100, jogorogoMax: 100 },
];
