/*
  # Insert All 135 Medicines Data

  1. Data Insertion
    - Inserts all 135 medicines with their Teguhan and Jogorogo max stock values
    - Each medicine will have proper teguhan_max and jogorogo_max values
    - Uses ON CONFLICT to avoid duplicates
    
  2. Notes
    - This is the complete medicine inventory for both locations
    - Stock settings will be created automatically by the application
*/

INSERT INTO medicines (id, name, teguhan_max, jogorogo_max, created_at, updated_at) VALUES
(gen_random_uuid(), 'ACETYLCYSTEINE CAP', 50, 50, now(), now()),
(gen_random_uuid(), 'ACYCLOVIR TAB 400MG', 50, 50, now(), now()),
(gen_random_uuid(), 'AMLODIPIN TAB 10MG', 150, 150, now(), now()),
(gen_random_uuid(), 'AMLODIPIN TAB 5MG', 150, 150, now(), now()),
(gen_random_uuid(), 'AMOXICILLIN SIRUP', 7, 7, now(), now()),
(gen_random_uuid(), 'AMOXILLIN TAB 500MG', 200, 200, now(), now()),
(gen_random_uuid(), 'ASAM MEFENAMAT 500 MG', 150, 150, now(), now()),
(gen_random_uuid(), 'ASAM TRANEXAMAT 500MG', 100, 100, now(), now()),
(gen_random_uuid(), 'ATTAPULGIT', 100, 100, now(), now()),
(gen_random_uuid(), 'ALOPURINOL 100 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'AMBROXOL TAB 30MG', 150, 150, now(), now()),
(gen_random_uuid(), 'AMBROXOL SIRUP', 5, 5, now(), now()),
(gen_random_uuid(), 'ACYCLOVIR CREAM', 25, 25, now(), now()),
(gen_random_uuid(), 'ALCOHOL SWAB', 25, 25, now(), now()),
(gen_random_uuid(), 'ASAM TRANEXAMAT AMP', 25, 25, now(), now()),
(gen_random_uuid(), 'BETAHISTIN TAB 6MG', 25, 25, now(), now()),
(gen_random_uuid(), 'BISOPROLOL TAB 2,5MG', 25, 25, now(), now()),
(gen_random_uuid(), 'BISOPROLOL TAB 5MG', 25, 25, now(), now()),
(gen_random_uuid(), 'BUFACORT - N CREAM', 25, 25, now(), now()),
(gen_random_uuid(), 'BUFANTACID TAB', 25, 25, now(), now()),
(gen_random_uuid(), 'BRONCHITIN TAB', 25, 25, now(), now()),
(gen_random_uuid(), 'BROCHIFAR PLUS TAB', 200, 200, now(), now()),
(gen_random_uuid(), 'BUFACOMB CREAM', 2, 2, now(), now()),
(gen_random_uuid(), 'BYE BYE FEVER', 5, 5, now(), now()),
(gen_random_uuid(), 'BIOMAG MPS TAB', 100, 100, now(), now()),
(gen_random_uuid(), 'CANDESARTAN TAB 16MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CANDESARTAN TAB 8MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CETIRIZIN TAB 10MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CETIRIZIN SIRUP', 5, 5, now(), now()),
(gen_random_uuid(), 'CEFIXIME 100MG', 150, 150, now(), now()),
(gen_random_uuid(), 'CEFIXIME 200MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CEFIXIME SIRUP', 10, 10, now(), now()),
(gen_random_uuid(), 'CEFTRIAXONE VIAL', 10, 10, now(), now()),
(gen_random_uuid(), 'CIPROFLOXACIN TAB 500MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CLOPIDOGREL TAB 75MG', 50, 50, now(), now()),
(gen_random_uuid(), 'CLINDAMYCIN TAB 300MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CODEIN TAB 10MG', 20, 20, now(), now()),
(gen_random_uuid(), 'COTRIMOXAZOLE TAB 960', 100, 100, now(), now()),
(gen_random_uuid(), 'CARMED CREAM', 1, 1, now(), now()),
(gen_random_uuid(), 'CHLORAMPHENICOL CAP 250 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CEFADROXIL SIRUP', 5, 5, now(), now()),
(gen_random_uuid(), 'CAPTROPIL TAB 12.5 MG', 50, 50, now(), now()),
(gen_random_uuid(), 'CAPTROPIL TAB 25 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'CURCUMA FORTE', 50, 50, now(), now()),
(gen_random_uuid(), 'CHLORAMPHENICOL SIRUP', 10, 10, now(), now()),
(gen_random_uuid(), 'CYANOCOBALAMIN VIAL', 5, 5, now(), now()),
(gen_random_uuid(), 'COMBIVENT', 10, 10, now(), now()),
(gen_random_uuid(), 'CHLORPROMAZINE TAB 100MG', 10, 10, now(), now()),
(gen_random_uuid(), 'CLOBETASOL CREAM 0.05%', 5, 5, now(), now()),
(gen_random_uuid(), 'DEXAMETASONE TAB 0,5MG', 200, 200, now(), now()),
(gen_random_uuid(), 'DEXAMETASONE TAB 0,75MG', 100, 100, now(), now()),
(gen_random_uuid(), 'DIAZEPAM TAB 2MG', 20, 20, now(), now()),
(gen_random_uuid(), 'DIMENHIDRINATE TAB 50 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'DEMACOLIN', 100, 100, now(), now()),
(gen_random_uuid(), 'DOMPERIDONE 10 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'DICLOFENAC POTASIUM 50 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'DANEURON', 50, 50, now(), now()),
(gen_random_uuid(), 'DICLOFENAC CREAM', 5, 5, now(), now()),
(gen_random_uuid(), 'DIPENHYDRAMINE HCL', 100, 100, now(), now()),
(gen_random_uuid(), 'DEXAMETHASONE AMP', 20, 20, now(), now()),
(gen_random_uuid(), 'DERMA PLAST', 10, 10, now(), now()),
(gen_random_uuid(), 'EPERISONE TAB 50 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'EPINEPHRINE AMP', 5, 5, now(), now()),
(gen_random_uuid(), 'FLUNARIZIN TAB', 100, 100, now(), now()),
(gen_random_uuid(), 'FUROSEMIDE TAB 40MG', 50, 50, now(), now()),
(gen_random_uuid(), 'FOLIC ACID TAB', 50, 50, now(), now()),
(gen_random_uuid(), 'GABAPENTIN CAP 100MG', 50, 50, now(), now()),
(gen_random_uuid(), 'GLIMEPIRIDE TAB 4 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'GLIMEPIRIDE TAB 2 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'GUAIFENESIN TAB 100 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'GENTAMICIN SULFATE 0.1%', 10, 10, now(), now()),
(gen_random_uuid(), 'GOM', 50, 50, now(), now()),
(gen_random_uuid(), 'GEL', 5, 5, now(), now()),
(gen_random_uuid(), 'HYPAVIX', 100, 100, now(), now()),
(gen_random_uuid(), 'HUFAMAG SIRUP', 10, 10, now(), now()),
(gen_random_uuid(), 'IBUPROFEN 400MG', 100, 100, now(), now()),
(gen_random_uuid(), 'IBUPROFEN SIRUP', 10, 10, now(), now()),
(gen_random_uuid(), 'INFUS SET', 10, 10, now(), now()),
(gen_random_uuid(), 'ISOSORBIDE DINITRATE', 50, 50, now(), now()),
(gen_random_uuid(), 'KETOKONAZOLE 200MG', 50, 50, now(), now()),
(gen_random_uuid(), 'KETOCONAZOLE CREAM', 10, 10, now(), now()),
(gen_random_uuid(), 'KETOROLAC AMP', 20, 20, now(), now()),
(gen_random_uuid(), 'KASSA', 10, 10, now(), now()),
(gen_random_uuid(), 'KETOPROFEN AMP', 100, 100, now(), now()),
(gen_random_uuid(), 'LANSOPRAZOLE 30 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'LEVOFLOXACIN 500MG', 100, 100, now(), now()),
(gen_random_uuid(), 'LIDOCAINE AMP', 50, 50, now(), now()),
(gen_random_uuid(), 'MELOXICAM 15MG', 100, 100, now(), now()),
(gen_random_uuid(), 'MEROPENEM VIAL', 5, 5, now(), now()),
(gen_random_uuid(), 'METRONIDAZOLE TAB 500MG', 100, 100, now(), now()),
(gen_random_uuid(), 'METYLPREDNISOLON 4MG', 100, 100, now(), now()),
(gen_random_uuid(), 'METYLPREDNISOLON 8MG', 100, 100, now(), now()),
(gen_random_uuid(), 'METRONIDAZOLE INFUS', 5, 5, now(), now()),
(gen_random_uuid(), 'METRONIDAZOLE SIRUP', 5, 5, now(), now()),
(gen_random_uuid(), 'METAMIZOLE VIAL', 5, 5, now(), now()),
(gen_random_uuid(), 'METFORMIN 500 MG', 100, 100, now(), now()),
(gen_random_uuid(), 'MIZONAZOLE 2% CREAM', 10, 10, now(), now()),
(gen_random_uuid(), 'NACL INFUS 0,9%', 10, 10, now(), now()),
(gen_random_uuid(), 'NUFACORT CREAM', 10, 10, now(), now()),
(gen_random_uuid(), 'OMEPRAZOLE 20MG CAP', 200, 100, now(), now()),
(gen_random_uuid(), 'ONDANSETRON TAB 4MG', 200, 100, now(), now()),
(gen_random_uuid(), 'ONDANCENTRON AMP', 20, 20, now(), now()),
(gen_random_uuid(), 'OMEPRAZOLE VIAL', 10, 10, now(), now()),
(gen_random_uuid(), 'PANTOPRAZOLE VIAL', 5, 5, now(), now()),
(gen_random_uuid(), 'PARACETAMOL INFUS', 5, 5, now(), now()),
(gen_random_uuid(), 'PARACETAMOL SIRUP', 10, 10, now(), now()),
(gen_random_uuid(), 'PARACETAMOL TAB 500MG', 200, 200, now(), now()),
(gen_random_uuid(), 'PLESTERIN', 25, 25, now(), now()),
(gen_random_uuid(), 'PRONEURON', 20, 20, now(), now()),
(gen_random_uuid(), 'PERMETHRIN 5%', 2, 2, now(), now()),
(gen_random_uuid(), 'PEHACAIN', 10, 10, now(), now()),
(gen_random_uuid(), 'RANITIDIN TAB 150MG', 200, 200, now(), now()),
(gen_random_uuid(), 'RECODRYL HCL VIAL', 5, 5, now(), now()),
(gen_random_uuid(), 'RL INFUS', 5, 5, now(), now()),
(gen_random_uuid(), 'RANITIDINE AMP', 30, 30, now(), now()),
(gen_random_uuid(), 'RIVANOL', 1, 1, now(), now()),
(gen_random_uuid(), 'SALBUTAMOL 2MG', 100, 100, now(), now()),
(gen_random_uuid(), 'SALBUTAMOL 4MG', 50, 50, now(), now()),
(gen_random_uuid(), 'SIMVASTATIN 10MG', 100, 100, now(), now()),
(gen_random_uuid(), 'SPASMINAL (PCT + HYOSCINE)', 100, 100, now(), now()),
(gen_random_uuid(), 'SALBUTAMOL SIRUP', 25, 25, now(), now()),
(gen_random_uuid(), 'SPUIT 1 CC', 25, 25, now(), now()),
(gen_random_uuid(), 'SPUIT 3 CC', 100, 100, now(), now()),
(gen_random_uuid(), 'SPUIT 5 CC', 50, 50, now(), now()),
(gen_random_uuid(), 'SPUIT 10 CC', 10, 10, now(), now()),
(gen_random_uuid(), 'STRIP ASAM URAT', 25, 25, now(), now()),
(gen_random_uuid(), 'STRIP GULA', 25, 25, now(), now()),
(gen_random_uuid(), 'STRIP KOLESTEROL', 10, 10, now(), now()),
(gen_random_uuid(), 'THIAMPHENICOL', 150, 150, now(), now()),
(gen_random_uuid(), 'VITAMIN C', 50, 50, now(), now()),
(gen_random_uuid(), 'VENFLON 18G', 5, 5, now(), now()),
(gen_random_uuid(), 'VENFLON 24G', 50, 50, now(), now()),
(gen_random_uuid(), 'WING NEEDLE NO 25', 50, 50, now(), now()),
(gen_random_uuid(), 'ZINC 10MG', 100, 100, now(), now()),
(gen_random_uuid(), 'ZINC 20MG', 100, 100, now(), now())
ON CONFLICT (name) DO NOTHING;